### ISSUE TITLE
first error

### ISSUE THREAD

**Issue by kdurant** [xleng/YCM_WIN_X86#1]
![qq20131226164019](https://f.cloud.github.com/assets/2704364/1809812/68672d9c-6e09-11e3-9aa2-f3b5a9c08220.jpg)

I clone this plugin into bundle directory, open vim, and display it. Don't config it in _vimrc

**Comment by xleng** [comment]
can you show me more details about the environment you used?

**Comment by xleng** [comment]
The  NOTE section in this site (https://bitbucket.org/Haroogan/vim-youcompleteme-for-windows/src) described your problem, please have a try.
